name: Docker Pipeline

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Buildx for multi-platform builds

      - name: Cache Docker layers
        uses: actions/cache@v2  # Cache Docker layers to speed up subsequent builds
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        run: |
          docker build -t my-node-app .
          docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d
